### ISSUE TITLE
Please, update your site https://react-hint.js.org/

### ISSUE THREAD

**Issue by nasushkov** [slmgc/react-hint#11]
Hi
Just found this library. Please, update the example on your site https://react-hint.js.org/
It seems that it the example uses an outdated version of this library

**Comment by madkarlsson** [comment]
+1
caused quite some confusion and had to find a [closed issue ](https://github.com/slmgc/react-hint/issues/8) to figure out how to do what should be simple stuff

**Comment by slmgc** [comment]
Yep, the samples need to be updated, I'll try to do it this weekend.

**Comment by slmgc** [comment]
Updated the website with the latest examples from react-hint v3.
