### ISSUE TITLE
Support for Children

### ISSUE THREAD

**Issue by tolrodco** [slmgc/react-hint#14]
While I could develop this by forking, I thought it would be helpful for the community to add support for child elements where the tooltip could accept HTML components. 

My use cases are specific to what I need, but, I think it would be helpful to support HTML within the tooltip itself.

Specially, when you would like to display certain elements with CSS styles, or, when presenting limited tabular data using HTML elements could be supported.

**Comment by slmgc** [comment]
Hi, could you describe your use-case in detail? If you will be able to provide a repro that would be really useful as it seems that the current implementation already supports all what's needed to render any html content.

**Comment by tolrodco** [comment]
Sure, unless I missed it, the way I am thinking is supporting children through the use of the ReactHint tag example, taking the child elements to be rendered in the hint without the need to create a function to support the additional elements:

```
<ReactHint
    persist
    attribute="data-custom"
    className="react-hint__custom"
    events={{ hover: true }}
    >
    <div className="head">
        <div className="columnA">Column A</div>
        <div className="columnB">Column B</div>
    </div>
    <div className="content">
        <div className="column">Dataset 1</div>
        <div className="column">Dataset 2</div>
    </div>
</ReactHint>

<span data-custom className="hint fa fa-info"></span>
```

The breakdown could be checking to see if there are child elements, if true, the code would be smart enough to then use the attributes of the parent to establish the appropriate elements:

##### On hover:
``` 
<div style="position: relative" class="react-hint__custom react-hint__custom--bottom">
    <div className="head">
        <div className="columnA">Column A</div>
        <div className="columnB">Column B</div>
        <div className="content">
            <div className="column">Dataset 1</div>
            <div className="column">Dataset 2</div>
        </div>
    </div>
</div>
```

**Comment by slmgc** [comment]
Ok, I see your case. But I believe it's perfectly doable with the current API:

```jsx
const renderContent = (target, content) =>
    <div className="head">
        <div className="columnA">Column A</div>
        <div className="columnB">Column B</div>
        <div className="content">
            <div className="column">Dataset 1</div>
            <div className="column">Dataset 2</div>
        </div>
    </div>

<ReactHint
    persist
    attribute="data-custom"
    className="react-hint__custom"
    events={{ hover: true }}
    onRenderContent={renderContent}
 />

<span data-custom className="hint fa fa-info"></span>
```

The downside I see with the proposal to use children is that it won't cover use-cases with multiple templates or the data, which is dependant on the data-attribute of the element. This is covered by the `onRenderContent` property, e.g.:

```jsx
const renderDefaultTemplate = (target, content) => {
    const {info} = target.dataset
    return info
        ? <div className="content">
            <div className="additional-info">{info}</div>
            {content}
        </div>

        : <div className="content">{content}</div>
}

const renderTemplate1 = (content) =>
    <div className="content">
        <div className="column">{content}</div>
    </div>

const renderTemplate2 = (content) =>
    <div className="head">
        <div className="column">{content}</div>
    </div>

const renderContent = (target, content) =>
    switch (content) {
        case 1: return renderTemplate1(content)
        case 2: return renderTemplate2(content)
        ...
        default: return renderDefaultTemplate(target, content)
    }

<ReactHint
    persist
    attribute="data-custom"
    className="react-hint__custom"
    events={{ hover: true }}
    onRenderContent={renderContent}
 />

// this will show a tooltip with the template1
<span data-custom="1" className="hint fa fa-info"></span>

// this will show a tooltip with the template2
<span data-custom="2" className="hint fa fa-info"></span>

// this will show a tooltip with the default template
<span data-custom className="hint fa fa-info"></span>

// this will show a tooltip with the default template with additional information
<span data-custom data-info="some value" className="hint fa fa-info"></span>
```

I don't think this is easily implementable with children only. Is there some specific issue which is not covered by the current API, which you want to resolve with the children support?

I like the [Zen of Python](https://en.wikipedia.org/wiki/Zen_of_Python), specifically this principle:
"There should be one—and preferably only one—obvious way to do it."

Hope this helps!

**Comment by slmgc** [comment]
Resolving, for now. Please feel free to re-open in case of any issues.

**Comment by tolrodco** [comment]
Thank you for clarifying, and, providing a clear example--really helpful.

**Comment by slmgc** [comment]
I am working on the next API, it's halfway there, but I would like to get as much feedback as possible about all the inconveniences with the current API and have a proper discussion around the new API. If you could join the discussion it would be awesome: https://github.com/slmgc/react-hint/issues/46
