### ISSUE TITLE
Hint doesn't re-render if data-rh is changed and hint is visible

### ISSUE THREAD

**Issue by ayal** [slmgc/react-hint#15]
Say that I have a div with data-rh={this.state.hintText}, on hover it shows.
Let's say I have an onClick on that element and when clicked I change state.hintText to something else - the element re-renders but the hint stays the same.

Only after mouseout/in does it renders correctly.

Could not find a workaround with available methods.

**Comment by slmgc** [comment]
You can do something like this: get the instance of `ReactHint`
```jsx
<ReactHint events ref={(ref) => this.instance = ref} />
```
And then call `this.instance.forceUpdate()` when you need to update the contents of the tooltip. Let me know if it solves your issue.

**Comment by slmgc** [comment]
@ayal closing the issue, feel free to reopen in case the solution doesn't work for you.

**Comment by ayal** [comment]
Hey, thanks for your quick reply and sorry for my late reply. I tried this before and it didn't work - only now noticed I had two instances of <ReactHint .../> in my code since in the readme example you put two instances and it's a bit confusing. Anyways it works with one instance using the "forceupdate" solution. Thanks.

**Comment by slmgc** [comment]
I am working on the next API, it's halfway there, but I would like to get as much feedback as possible about all the inconveniences with the current API and have a proper discussion around the new API. If you could join the discussion it would be awesome: https://github.com/slmgc/react-hint/issues/46
