### ISSUE TITLE
The website is broken

### ISSUE THREAD

**Issue by kajyr** [slmgc/react-hint#16]
Hi! Thanks for react-hint, I am using it and having a good time :) I wanted to adopt it on a bigger project of mine, but but website https://react-hint.js.org is at the moment broken, and I cannot demo the tooltip to the rest of the team.

The error is

```
Uncaught ReferenceError: ReactHintFactory is not defined
        at react-hint.js.org/:335
```

Thanks,

**Comment by slmgc** [comment]
It might have been a transient outage of https://unpkg.com. I don't see any issues ATM, checked with Safari, Chrome, and Firefox. Could you check it again? If it's still broken for you, could you also check the network tab for any 4xx?

**Comment by kajyr** [comment]
Yes nw it works perfectly! :) Sorry for the issue :)
