### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by srmagura** [slmgc/react-hint#19]
Thank you for this library - it works very well in Chrome and Firefox.

I have run into two problems when testing it in IE 11 though. Does react-hint support IE?

The most noticeable issue is that, in IE, the tooltips do not appear in the demo (https://react-hint.js.org/).

The other issue I am having in IE is that hovering over a select that has a tooltip causes a React "Maximum update depth exceeded". There is no issue in other browsers. I can try to provide a small example reproducing the error if you want.

**Comment by slmgc** [comment]
Hi, there was no initial intent to support IE11 or older, but I can try looking into this issue.

**Comment by srmagura** [comment]
That's fine. Please don't feel like you need to add IE support on my behalf.

If anyone else is interested, [here](https://gist.github.com/srmagura/b57c1ec54f523804662d79e463d7b168) is the quick & dirty fallback I am using for IE. Emphasis on the "dirty".

**Comment by slmgc** [comment]
Sorry for a late fix, it took me a while to find some spare time to debug this issue. Should work fine in IE11.

**Comment by srmagura** [comment]
Tested it in my application and it works. Great job!

**Comment by slmgc** [comment]
I am working on the next API, it's halfway there, but I would like to get as much feedback as possible about all the inconveniences with the current API and have a proper discussion around the new API. If you could join the discussion it would be awesome: https://github.com/slmgc/react-hint/issues/46
