### ISSUE TITLE
Global Settings in ReactHint Props

### ISSUE THREAD

**Issue by jcuenod** [slmgc/react-hint#2]
It would be great if we could provide global settings/defaults to ReactHint through the component, for example:

    <ReactHint displayDelay=100 hideDelay=300 transition="slide" />

Also, supporting those settings would be great as well ;)

**Comment by slmgc** [comment]
@jcuenod yep. I plan to add these settings in the future update. Btw, do you think it makes sense to add both show/hide delay settings?

**Comment by slmgc** [comment]
Released v2, added delay-related global settings

**Comment by jcuenod** [comment]
@slmgc Great! Sorry - don't know how I missed your question on the previous message.
The reason I had thought hide delay would be handy is because it gives the user a chance to hover on the hint if it's a harder target.

**Comment by slmgc** [comment]
@jcuenod at this point a unified delay setting for both hide/show was implemented. This can be easily extended later if there will be a need for it.

**Comment by jcuenod** [comment]
@slmgc oh ja! thanks for taking the suggestion of the global setting.

**Comment by slmgc** [comment]
I am working on the next API, it's halfway there, but I would like to get as much feedback as possible about all the inconveniences with the current API and have a proper discussion around the new API. If you could join the discussion it would be awesome: https://github.com/slmgc/react-hint/issues/46

**Comment by jcuenod** [comment]
Thanks for the invitation but I haven't been using `react-hint` for a while now so I'm probably not the ideal person.
