### ISSUE TITLE
Accessibility using ARIA tags

### ISSUE THREAD

**Issue by ambrwlsn** [slmgc/react-hint#24]
Hey, I am wondering if it's possible to ensure the tooltip is accessible. Perhaps using one of the examples listed [here](http://pauljadam.com/demos/aria-role-tooltip.html)? Have you ever considered the use of ARIA tags for the tooltip? Thanks

**Comment by slmgc** [comment]
Hi, I don't want to bind tooltips to some existing attributes (title, aria-*, etc) as it might not always be an intent, thus they use an explicit custom attribute by default. You can change the default attribute of the tooltip to "aria-describedby", for example, this should cover your case.

**Comment by slmgc** [comment]
Resolving, please feel free to re-open in case you'll have any concerns.
