### ISSUE TITLE
Hint positioning both vertically and horizontally

### ISSUE THREAD

**Issue by matias-pool** [slmgc/react-hint#26]
It would be great if it was possible to position the hint both vertically and horizontally, like `position="topLeft"` or `horizontalPosition="left" verticalPosition="top"` or similar.

https://github.com/slmgc/react-hint/blob/1cb28df13617bb7b07650c44356738d68a5fdccf/src/index.js#L146

We extended the switch statement in `getHintData`  to handle our particular use case, but this approach may not be practical as a general solution.

```javascript
      case 'topLeft':
        top = 0;
        left = -hintWidth;
        break;
```

What would be your suggestion?

**Comment by slmgc** [comment]
Hi, that's a good idea, actually. I need to check how it's usually implemented. We can have a discussion here about the implementation details. I would prefer `top-left` to `topLeft` though. I am not sure if the tooltip should be positioned exactly at the edge of the element or should it be close to the edge. What do you think? What's your use-case? Can you append some screenshots?

**Comment by matias-pool** [comment]
Our use case is a multilingual questionnaire where the user should be able to listen to an audio clip 
for any label. We are using `react-hint` to wrap the audio player. Extending the case statement is the simplest way, but it adds many lines of code. 

![react-hint](https://user-images.githubusercontent.com/40055649/41457969-f8856246-708d-11e8-84e4-a2968afd5717.gif)

**Comment by matias-pool** [comment]
For a more dynamic approach maybe a `"top-left".split('-')` could be done, and then top and left would be set for every item.

In a pseudo code fashion I mean:

```javascript
const positions = "top-left".split('-');

if (positions.includes('top')) {
  top = 0;
}

if (positions.includes('left')) {
  left = -hintWidth;
}
```

**Comment by matias-pool** [comment]
I'm adding a [patch](https://github.com/slmgc/react-hint/files/2105719/patch.zip) to show how it could be done.

* There is no sanity checking or error handling
* A `case 'center': left = 0` could be added for consistency
* The other switch must do something similar at 
https://github.com/slmgc/react-hint/blob/1cb28df13617bb7b07650c44356738d68a5fdccf/src/index.js#L117

**Comment by slmgc** [comment]
@matias-pool after a second thought, it doesn't seem to be a simple decision. I don't think there is a universal solution to align tooltips vertically + horizontally. For example, let's take "bottom-left", there are 3 possible implementations:

1. The arrow is centered horizontally:

<img width="314" alt="screen shot 2018-08-02 at 12 48 24 pm" src="https://user-images.githubusercontent.com/5236786/43608714-a410abbe-9656-11e8-9034-2f1b152d6886.png">

2. The arrow is at the edge of the tooltip:

<img width="268" alt="screen shot 2018-08-02 at 12 49 54 pm" src="https://user-images.githubusercontent.com/5236786/43608762-d6ade456-9656-11e8-948b-576266d3182b.png">

3. Your proposal shifts the whole tooltip to the left by its width (in this case, the arrow should be probably hidden completelly):

<img width="482" alt="screen shot 2018-08-02 at 1 15 04 pm" src="https://user-images.githubusercontent.com/5236786/43608804-fc160b60-9656-11e8-96c1-b3ed92b88a31.png">

I don't think there could be a solution that fits everyone's needs and I don't want to include something which won't be useful for majority of users. Do you have thoughts on this?

**Comment by slmgc** [comment]
Closing this issue for now as there is no obvious solution which fits all cases.

**Comment by slmgc** [comment]
I am working on the next API, it's halfway there, but I would like to get as much feedback as possible about all the inconveniences with the current API and have a proper discussion around the new API. If you could join the discussion it would be awesome: https://github.com/slmgc/react-hint/issues/46
