### ISSUE TITLE
ARIA compilant

### ISSUE THREAD

**Issue by Kikobeats** [slmgc/react-hint#28]
Hello,

I think could easy make this library ARIA compliant

As referenced:

- http://accessibility.athena-ict.com/aria/examples/tooltip.shtml
- http://pauljadam.com/demos/aria-role-tooltip.html

**Comment by slmgc** [comment]
Hi @Kikobeats,

That's a good idea. Does it mean that the tooltip itself needs to have only `role="tooltip"` attribute to be ARIA-compliant?

**Comment by Kikobeats** [comment]
Not just role, adding an ARIA label when the tooltip is hidden or no 🙂

**Comment by Kikobeats** [comment]
A relevant reference: https://github.com/egoens/react-aria-tooltip/blob/c1679fc4c252a382c3e7115f2be20ff0bfa2abab/src/tooltip-content.jsx#L12

**Comment by slmgc** [comment]
@Kikobeats it doesn't make any sense to add such a label as there is no dom element to show the hidden status :)

**Comment by slmgc** [comment]
I am working on the next API, it's halfway there, but I would like to get as much feedback as possible about all the inconveniences with the current API and have a proper discussion around the new API. If you could join the discussion it would be awesome: https://github.com/slmgc/react-hint/issues/46
