### ISSUE TITLE
Allow setting different show & hide delay

### ISSUE THREAD

**Issue by prymitive** [slmgc/react-hint#29]
Is this possible? Looking at the code I only see a single timer for this, is there any hook I can use to customize this?
I want to have long show delay but a short hide to avoid spamming the UI with tooltip popups as user moves the mouse around. Tooltips should only show up if user is confused what given control does and pauses for a second, but once tooltip is visible and user moves the cursor away I don't want to keep that old popup visible for another second, it should hide instantly when not needed.
Thanks!

**Comment by slmgc** [comment]
Hi, I can introduce this change, for sure.

**Comment by willadamskeane** [comment]
Any updates on this?

**Comment by slmgc** [comment]
@willadamskeane not yet, but I will try working on that this weekend

**Comment by slmgc** [comment]
@prymitive @willadamskeane added show/hide delay

**Comment by willadamskeane** [comment]
A little issue I've noticed - the hide delay seems to be ignored if you immediately hover over an adjacent component with a tooltip attached.

**Comment by slmgc** [comment]
I am working on the next API, it's halfway there, but I would like to get as much feedback as possible about all the inconveniences with the current API and have a proper discussion around the new API. If you could join the discussion it would be awesome: https://github.com/slmgc/react-hint/issues/46
