### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by cimi** [slmgc/react-hint#3]
Nice library! I've just stumbled upon it today and played with it a bit.

I've tried using react-hint to add tooltips to SVG elements and it doesn't work. I'm guessing it's because it tries to inject 'plain' DOM elements (`div`, `span`) as the wrappers for the tooltip and that doesn't play well with SVG.

I've used [redux-tooltip](https://github.com/kuy/redux-tooltip) successfully with SVG. That library allows the user to [specify a custom wrapper](https://github.com/kuy/redux-tooltip#originwrapbytagname), for example if I put `g` as my preferred tag everything works nicely. Not sure how easy a change this is to make or there is any other SVG specific logic involved besides just switching tags.

**Comment by slmgc** [comment]
@cimi oh, that's an interesting use-case! Could you post a link to a fiddle with an example? I would like to figure out what's wrong as it seems that react-hint should work. Unless it's being placed inside of the SVG.

**Comment by slmgc** [comment]
I've checked react-hint with SVG and it worked just fine for me:
![screen shot 2017-11-17 at 21 37 45](https://user-images.githubusercontent.com/5236786/32976206-ae705506-cbdf-11e7-9ddd-1b5b66e78a73.png)
 Please reopen in case you'll be able to provide a repro.

**Comment by mockey-jockey** [comment]
using SVG react hint not working in IE11,Except IE for all browser working well.kindly help to resolve this

**Comment by mockey-jockey** [comment]
@cimi @slmgc -->I fixed this issue ,**element.dateset** not working in IE,

```
<ReactHint events delay={100} onRenderContent={(element) => {
          if (element && element.dataset && element.dataset.rh) {
            return (<div className="react-hint__content">
              {element.dataset.rh.split("\n").map((content, i) =>
                <span key={i}>{content} {content && <br />}</span>
              )
              }
            </div>)
          }
          return null;

        }} />
```


changed to -------


```
<ReactHint events delay={100} onRenderContent={(element) => {
           if (element) {
            let datasetValue = element.getAttribute("data-rh");
            if(datasetValue){
              return (<div className="react-hint__content">
                {datasetValue.split("\n").map((content, i) =>
                  <span key={i}>{content} {content && <br />}</span>
                )
                }
              </div>)
            }                               
          }
          return null;

        }} />
```

Above code will work perfectly in IE11

**Comment by cimi** [comment]
Sorry for the super late reply!

> Unless it's being placed inside of the SVG.

Yes, this is/was the problem. We've fixed and we're happy users of react-hint.

**Comment by slmgc** [comment]
I am working on the next API, it's halfway there, but I would like to get as much feedback as possible about all the inconveniences with the current API and have a proper discussion around the new API. If you could join the discussion it would be awesome: https://github.com/slmgc/react-hint/issues/46
