### ISSUE TITLE
Show tooltip on disabled buttons

### ISSUE THREAD

**Issue by drosko** [slmgc/react-hint#30]
Tooltip will not show on a disabled button.  Is this possible to fix?  I'd be happy to take a stab at it if you think it is doable. I tried wrapping the button in a span with the data-rh attribute, but that didn't work.

**Comment by slmgc** [comment]
Hi, let me try experimenting with this a little bit. I'll get back to you with my findings.

**Comment by slmgc** [comment]
Hi! Sorry for such a long delay :/ Inline elements won't work, but block elements do work when you wrap a disabled button. Here's what you can do:

```jsx
<div data-rh="Disabled button tooltip" style={{display: 'inline-block'}}>
	<button disabled>Disabled button</button>
</div>
```

Hope this helps!

**Comment by drosko** [comment]
👍

**Comment by slmgc** [comment]
I am working on the next API, it's halfway there, but I would like to get as much feedback as possible about all the inconveniences with the current API and have a proper discussion around the new API. If you could join the discussion it would be awesome: https://github.com/slmgc/react-hint/issues/46
