### ISSUE TITLE
does this have typescript definitions? 

### ISSUE THREAD

**Issue by paigeflourin** [slmgc/react-hint#33]
i'd like to use it for my project but my project uses typescript. can it work in typescript?

**Comment by slmgc** [comment]
It doesn't have typescript definitions, but I believe it should be pretty easy to use with typescript without definitions or create ones from scratch. You are welcome to contribute :3

**Comment by paigeflourin** [comment]
How do I make a component as the content? sorry i am quite confused with the docs

**Comment by slmgc** [comment]
Hi, you can use `onRenderContent` property to render any component as a tooltip's content:

```jsx
<ReactHint events onRenderContent={(target, content) =>
    <SomeCustomComponent content={content} />
} />
```

Feel free to ping me if this doesn't answer your question.

**Comment by whitepotato** [comment]
Could not find a declaration file for module 'react-hint'. 
  Try `npm install @types/react-hint` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-hint';`  TS7016

**Comment by slmgc** [comment]
@whitepotato that's because no one contributed type definitions, but you a welcome to do it
