### ISSUE TITLE
get _ref on hover in my component

### ISSUE THREAD

**Issue by vcebotari** [slmgc/react-hint#4]
hello, can you tell me if it's possible to get hovered element ?
i want to replace some data in custom tooltip from 'target' data attributes

**Comment by vcebotari** [comment]
and another question, how to hide tooltip even i hover it self?

**Comment by slmgc** [comment]
Hi! I'm working on a new release which should be ready by the end of this week.

The new 2.0 release will support additional options like delay time before showing a tooltip, hide a tooltip on hover, disable hover events to trigger a tooltip programmatically, custom tooltips, multiple tooltips with different settings, etc.

As for your former question: can you post a link to a fiddle with an example of what you are trying to achieve? I might be able to help you, just need to understand the use-case.

**Comment by vcebotari** [comment]
hi! thanks, will wait for the new one.

**Comment by slmgc** [comment]
v2 was released, let me know if you have any issues with it

**Comment by slmgc** [comment]
I am working on the next API, it's halfway there, but I would like to get as much feedback as possible about all the inconveniences with the current API and have a proper discussion around the new API. If you could join the discussion it would be awesome: https://github.com/slmgc/react-hint/issues/46
