### ISSUE TITLE
Is there a duration parameter? 

### ISSUE THREAD

**Issue by Vpet95** [slmgc/react-hint#40]
A duration parameter would be nice, to configure how long the tooltips stay visible. Based on the documentation I don't believe there is - correct me if I'm wrong!

**Comment by slmgc** [comment]
There is one. There is a property in the docs called "delay" which accepts either number or an object, e.g.
```jsx
<ReactHint delay={{show: 0, hide: 1000}} /> // hide the tooltip after 1 second
```
Hope this helps!

**Comment by slmgc** [comment]
Closing, please feel free to reopen in case you still have questions.

**Comment by slmgc** [comment]
I am working on the next API, it's halfway there, but I would like to get as much feedback as possible about all the inconveniences with the current API and have a proper discussion around the new API. If you could join the discussion it would be awesome: https://github.com/slmgc/react-hint/issues/46
