### ISSUE TITLE
Tooltip content rendering inline

### ISSUE THREAD

**Issue by dsarfati** [slmgc/react-hint#41]
My tooltip content is rendering at the position of the `ReactHint` instead of floating above the element with the `data-rh`. I am including `<ReactHint autoPosition events />` in my component, not at the `<App />` level. Could this cause problems?

Example:
```js
class ComponentWithTooltip extends Component<Props> {
  render() {
    return (
      <div >
         <ReactHint autoPosition events />
         <button data-rh="tooltip 1">Hover me 1 !</button>
         <button data-rh="tooltip 2">Hover me 2 !</button>
      </div>
    )
  }
}
```

**Comment by slmgc** [comment]
@dsarfati Hi, yes, this could be the source of the issue. You shouldn't include ReactHint in each component with tooltips because this will create multiple instances of ReactHint.

**Comment by dsarfati** [comment]
Thanks for the quick response! It looks like I was missing the `import 'react-hint/css/index.css'`. I'll work on moving my ReactHint out of the component.

**Comment by slmgc** [comment]
I am working on the next API, it's halfway there, but I would like to get as much feedback as possible about all the inconveniences with the current API and have a proper discussion around the new API. If you could join the discussion it would be awesome: https://github.com/slmgc/react-hint/issues/46
