### ISSUE TITLE
Multi-line

### ISSUE THREAD

**Issue by vadbut** [slmgc/react-hint#44]
Hi, 

Is it possible to show multiple lines in a popup for a very basic case?
```
<ReactHint autoPosition events />
<button data-rh="tooltip 1">Hover me 1 !</button>
```
I tried using "\n" symbol but it didn't work.

**Comment by slmgc** [comment]
Hi, as you might know, browsers ignore `\r\n` characters. To have a multiline output you have to use tags: `<br>`, `<p>`, etc. For your case, if you still want to render multiline characters with `\n` symbol, you can use `onRenderContent` property:

```jsx
<ReactHint events onRenderContent={(target, content) =>
    <div dangerouslySetInnerHTML={{__html: String(content).replace('\n', '<br>')}} />
} />
```

P.S. You can read more about `dangerouslySetInnerHTML` and XSS attacks threat here: https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml

Hope this helps!

**Comment by adamPrune** [comment]
I tried using `<br>` tag inside the `data-rh='some text'` text but it seems that it's not possible, and I need to use the onRenderContent method to make a multiline. Is that correct?

**Comment by slmgc** [comment]
@adamPrune that's correct, you'll have to use the approach from the example above.
