### ISSUE TITLE
[Bug] Tooltip breaks in specific cases, causes infinite re-renders and crashes

### ISSUE THREAD

**Issue by essensx** [slmgc/react-hint#49]
Not completely sure what is happening here, seems since the lib can't properly position the tooltip, it tries to reposition it infinitely.

Sample: https://codesandbox.io/s/awesome-ellis-yyjyf

### Steps To Reproduce

* Open Chrome;
* Toggle device toolbar;
* Select Galaxy S5 as device (Tested on these specs https://i.imgur.com/l92uDY5.png);
* Click on "Hover me" element.

### Result

App crashes, React throws an exception of `setState` depth reached.

**Comment by ranihorev** [comment]
Here is a fix - https://github.com/slmgc/react-hint/pull/50

**Comment by essensx** [comment]
Any updates?

**Comment by slmgc** [comment]
@essensx whoah, looks like I totally missed that issue, sorry about that.
@ranihorev thanks a lot for the fix, I started the review, will try to check everything this weekend.

**Comment by davidesigner** [comment]
Hi @slmgc, could you merge the fix of @ranihorev #50 please? Thank you!

**Comment by slmgc** [comment]
Hi everyone, sorry for not responding on time :/
Merged and released a new version with the fix, thanks a lot @essensx and @ranihorev
