### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by hudochenkov** [slmgc/react-hint#6]
Thank you for your library!

What are breaking (and non-breaking) changes in v2? I can't find changelog anywhere. Would you mind add it, please?

**Comment by slmgc** [comment]
@hudochenkov hey :)
There were some breaking API changes and I agree, I need to add a changelog. I will try to do this within the next few days.

As for now, you can probably use [the link to the latest v1 "How to use" section]( https://github.com/slmgc/react-hint/tree/19b347021e964e224fdd61addb2ad646789814ee#how-to-use) as it lists all the parameters and shows some usage examples. Hope it helps!

**Comment by cawfeecoder** [comment]
I can't get React Hint to work with Infero :/ Keep getting a "Super must not be null" error in the console.

**Comment by slmgc** [comment]
@nfrush in order to use react-hint with Inferno, you need to install `inferno-compat` as it should have a compatible API, similar to React, as react-hint expects to see `createElement` & `Component`, when you initialize a new instance, e.g. `ReactHintFactory({createElement, Component})`:
```jsx
import Inferno from 'inferno-compat'
import {ReactHintFactory} from 'react-hint'
import 'react-hint/css/index.css'
const ReactHint = ReactHintFactory(Inferno)

...

<div>
    <ReactHint events />
    <p data-rh="tooltip">Works with Inferno!</p>
</div>
```

**Comment by slmgc** [comment]
@hudochenkov added [changelog](https://github.com/slmgc/react-hint/blob/master/CHANGELOG.md)

**Comment by hudochenkov** [comment]
Thank you very much!

**Comment by slmgc** [comment]
I am working on the next API, it's halfway there, but I would like to get as much feedback as possible about all the inconveniences with the current API and have a proper discussion around the new API. If you could join the discussion it would be awesome: https://github.com/slmgc/react-hint/issues/46

**Comment by hudochenkov** [comment]
I wish I could help. I'm not working on a project which uses your library for a long time now.
