### ISSUE TITLE
Error when building for production

### ISSUE THREAD

**Issue by riccardod** [slmgc/react-hint#9]
The compilation fails when building for production (npm run build) due to Webpack Uglify plugin.

Step to reproduce: 

```
1. create-react-app example
2. cd example 
3. npm run build  --> works
4. npm inistall -S react-hint
5. Add some react-hint code to the file App.js (as shown in the react-hint example)
6. npm start --> works
7. npm build --> will give you an error 'Failed to minify the code..'
```

The error seems due to the way "react-hint" is exported (http://bit.ly/2tRViJ9)
Temporary workaround: Copied and referenced the ReactHintFactory in my project directly and it worked.

**Comment by slmgc** [comment]
Thanks a lot for pointing this out!
Updated the `react-hint` npm package. Depending on the npm version, might require running:
```bash
rm -rf node_modules/ package-lock.json
```
